spring:
  datasource:
    url: jdbc:mysql://localhost:3306/olxmasterd
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: welcome
  jpa:
    hibernate.ddl-auto: update  
    properties:
       hibernate:
          dialect:org.hibernate.dialect.MYSQL8Dialect
  application:
    name: auth-source

server:
  port: 7000

  
     
eureka:
  instance:
    hostname: localhost 
    instance-id: ${spring.application.name}.{random.uuid} 
  client:
       register-with-eureka: true
       fetch-registry: true